# Web hooks configs
hooks:
  channels:
    - from-akka-apps-redis-channel
    - to-akka-apps-redis-channel
    - from-bbb-web-redis-channel
    - from-akka-apps-chat-redis-channel
    - from-akka-apps-pres-redis-channel
    - bigbluebutton:from-bbb-apps:meeting
    - bigbluebutton:from-bbb-apps:users
    - bigbluebutton:from-rap